# Site settings
title: We Make Thang
email: me@kahfei.com
description: > # this means to ignore newlines until "baseurl:"
  Interviews of makers
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wemakethang.com" # the base hostname & protocol for your site
twitter_username: kahfei
github_username:  kahfei

# Build settings
markdown: kramdown
